//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomBookingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking
    {
        public string RoomType { get; set; }
        public int NoOfRoomsBooked { get; set; }
        public string HotelName { get; set; }
        public int Id { get; set; }
        public string HotelAddress { get; set; }
        public int RoomId { get; set; }
    }
}
